# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiChangeWindow(object):
    def setupUi(self, change_window):
        change_window.setObjectName("change_window")
        change_window.resize(415, 330)
        self.gridLayout_2 = QtWidgets.QGridLayout(change_window)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(change_window)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.cb_drinks = QtWidgets.QComboBox(change_window)
        self.cb_drinks.setObjectName("cb_drinks")
        self.gridLayout.addWidget(self.cb_drinks, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(change_window)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(change_window)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.line_roasting = QtWidgets.QLineEdit(change_window)
        self.line_roasting.setObjectName("line_roasting")
        self.gridLayout.addWidget(self.line_roasting, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(change_window)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.line_id = QtWidgets.QLineEdit(change_window)
        self.line_id.setObjectName("line_id")
        self.gridLayout.addWidget(self.line_id, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(change_window)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.line_coast = QtWidgets.QLineEdit(change_window)
        self.line_coast.setObjectName("line_coast")
        self.gridLayout.addWidget(self.line_coast, 8, 1, 1, 1)
        self.line_ground = QtWidgets.QLineEdit(change_window)
        self.line_ground.setObjectName("line_ground")
        self.gridLayout.addWidget(self.line_ground, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(change_window)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.line_name = QtWidgets.QLineEdit(change_window)
        self.line_name.setObjectName("line_name")
        self.gridLayout.addWidget(self.line_name, 4, 1, 1, 1)
        self.line_volume = QtWidgets.QLineEdit(change_window)
        self.line_volume.setObjectName("line_volume")
        self.gridLayout.addWidget(self.line_volume, 9, 1, 1, 1)
        self.line_description = QtWidgets.QLineEdit(change_window)
        self.line_description.setObjectName("line_description")
        self.gridLayout.addWidget(self.line_description, 7, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(change_window)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        self.btn_change = QtWidgets.QPushButton(change_window)
        self.btn_change.setObjectName("btn_change")
        self.gridLayout.addWidget(self.btn_change, 10, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(change_window)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(change_window)
        QtCore.QMetaObject.connectSlotsByName(change_window)

    def retranslateUi(self, change_window):
        _translate = QtCore.QCoreApplication.translate
        change_window.setWindowTitle(_translate("change_window", "Change Window"))
        self.label_2.setText(_translate("change_window", "выбрать уже существющий напиток:"))
        self.label.setText(_translate("change_window", "id"))
        self.label_3.setText(_translate("change_window", "название сорта"))
        self.label_6.setText(_translate("change_window", "описание вкуса"))
        self.label_5.setText(_translate("change_window", "молотый/в зернах"))
        self.label_7.setText(_translate("change_window", "цена"))
        self.label_8.setText(_translate("change_window", "объем упаковки"))
        self.btn_change.setText(_translate("change_window", "создать"))
        self.label_4.setText(_translate("change_window", " степень обжарки"))
